# Generated by Django 3.1.12 on 2025-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Interviewer')], max_length=10),
        ),
    ]
