# Generated by Django 3.1.12 on 2025-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='topic_stats',
            field=models.JSONField(default=dict),
        ),
    ]
