# Generated by Django 3.1.12 on 2025-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_agentmemory_topic_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmemory',
            name='last_ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='last_exam_scores',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='agentmemory',
            name='sessions',
            field=models.JSONField(default=list),
        ),
    ]
